# Sistemas de recomendación basado en contenido
## Recomendador de peliculas

In [44]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
ruta = r"C:\Users\borja\Desktop\Github\Data-Analytics-Portfolio\04-IA-BigData\02-Sistemas-Recomendacion\01-recomendador-peliculas-contenido\data\peliculas_netflix.xlsx"

df = pd.read_excel(ruta)

In [46]:
df.head(20)

    id  ...                                        descripcion
0    1  ...  El patriarca de una familia de la mafia italoa...
1    2  ...  Las vidas de dos sicarios, un boxeador y la es...
2    3  ...  Batman se enfrenta al Joker, un criminal anarq...
3    4  ...  Un ladrón especializado en robar secretos del ...
4    5  ...  Un programador descubre que la realidad que co...
5    6  ...  Un hombre de buen corazón e intelecto limitado...
6    7  ...  Un artista sin recursos y una joven de la alta...
7    8  ...  Una familia humilde se infiltra poco a poco en...
8    9  ...  Un grupo de astronautas viaja a través de un a...
9   10  ...  Un general romano traicionado es reducido a es...
10  11  ...  Un hobbit hereda un anillo de poder capaz de d...
11  12  ...  Un parque temático con dinosaurios clonados a ...
12  13  ...  Los juguetes de un niño cobran vida cuando nad...
13  14  ...  Un niño mexicano apasionado por la música viaj...
14  15  ...  Un ogro solitario debe rescatar a una princesa...
15  16  ...  Una familia de superhéroes obligada a vivir en...
16  17  ...  Un comediante fracasado y marginado por la soc...
17  18  ...  Un joven baterista de jazz se somete a los mét...
18  19  ...  Una aspirante a actriz y un pianista de jazz i...
19  20  ...  Un joven afroamericano descubre una verdad per...

[20 rows x 4 columns]

In [47]:
#Sistema de recomendación basado en la descripción. Transformación del texto en numeros con la liberia a aplicar. 

vectorizer = TfidfVectorizer()
matriz_tfid = vectorizer.fit_transform(
    df["descripcion"]
)

In [48]:
vectorizer.get_feature_names_out()

array(['abuela', 'acabar', 'accidentalmente', 'acción', 'acepta',
       'aceptar', 'acompañado', 'acontecimientos', 'actriz', 'acude',
       'adinerada', 'adn', 'adopta', 'afroamericano', 'afrontan',
       'agente', 'agujero', 'ajeno', 'al', 'algunos', 'aliados',
       'alimentarse', 'alta', 'amenaza', 'amiga', 'amor', 'anarquista',
       'anciano', 'anillo', 'animal', 'aniversario', 'anonimato',
       'anterior', 'aparición', 'apasionado', 'apocalíptico', 'armas',
       'arrebataron', 'artista', 'artísticos', 'ascenso', 'asesinatos',
       'asesino', 'asesinó', 'aspirante', 'astronautas', 'ata',
       'aterradores', 'aterrorizada', 'aterrorizó', 'atrapar',
       'atraviesa', 'atraviesan', 'autodestrucción', 'ayuda', 'ayudar',
       'año', 'años', 'bahía', 'bailarina', 'ballet', 'banda',
       'baterista', 'batman', 'boda', 'bordo', 'borrar', 'boxeador',
       'brillante', 'brutales', 'buen', 'burro', 'busca', 'camarera',
       'campeón', 'campo', 'caníbal', 'caos', 'capaz', 'capitales',
       'capturado', 'casa', 'casi', 'caso', 'cazarrecompensas', 'cede',
       'ciudad', 'clandestinidad', 'clase', 'clonados', 'cobran', 'coma',
       'comediante', 'cometidos', 'compartida', 'comunidad', 'con',
       'concentración', 'conoce', 'consecuencias', 'consultorio',
       'contra', 'control', 'convertirse', 'convierte', 'corazón',
       'corporación', 'creada', 'criado', 'crimen', 'criminal',
       'criminales', 'cruel', 'cruza', 'cruzada', 'cuando', 'cuenta',
       'cumplir', 'célebre', 'de', 'debe', 'decide', 'dedicarse', 'del',
       'demostrar', 'dental', 'desaparecida', 'desaparición',
       'desarrolla', 'descomposición', 'desconocido', 'descubre',
       'desencadenando', 'desenterrar', 'desesperado', 'desierto',
       'despierta', 'destruir', 'destruirlo', 'destruirlos', 'detectives',
       'devastado', 'dibujante', 'dinosaurios', 'director', 'diseñado',
       'divorcio', 'doloroso', 'dolorosos', 'doméstica', 'dos', 'durante',
       'el', 'emperador', 'empieza', 'empleada', 'emprende', 'en',
       'encontrar', 'enfrenta', 'enfrentar', 'enfrentarse', 'enorme',
       'entidad', 'entrelazan', 'es', 'escapa', 'esclavo', 'espacial',
       'españa', 'especializado', 'espiral', 'esposa', 'estados',
       'exasesina', 'exigente', 'experimental', 'explorador', 'extremos',
       'fallan', 'familia', 'familiar', 'fantasma', 'fauno', 'fbi',
       'felicidad', 'fenómeno', 'figuras', 'filadelfia', 'fines', 'forma',
       'forzada', 'fracasado', 'francisco', 'freddie', 'futuro',
       'generaciones', 'general', 'giros', 'gladiador', 'globos',
       'gotham', 'gradualmente', 'granja', 'grupo', 'guerrera', 'gueto',
       'guiar', 'gusano', 'gánster', 'habitado', 'hasta', 'hereda',
       'herencia', 'hermana', 'hija', 'hijo', 'hijos', 'historia',
       'historias', 'hobbit', 'hogar', 'holmes', 'hombre', 'horror',
       'huir', 'humana', 'humanidad', 'humilde', 'humillantes', 'humor',
       'héroe', 'híbrido', 'icónico', 'idea', 'idealista', 'identificar',
       'imaginación', 'imperio', 'implantar', 'implicación',
       'importantes', 'imposible', 'imprevisibles', 'inaugural',
       'indígena', 'inesperada', 'inesperadas', 'inesperado', 'infantil',
       'infiltra', 'inhabitable', 'inicia', 'insistente', 'inspirados',
       'intelecto', 'inteligente', 'intentaron', 'investigadores',
       'investigan', 'investigar', 'italoamericana', 'jazz', 'joker',
       'joven', 'judío', 'juguete', 'juguetes', 'junto', 'justicia', 'la',
       'laberinto', 'ladrón', 'las', 'le', 'liberado', 'liberar',
       'limitado', 'llegada', 'lleno', 'llevado', 'lo', 'londres', 'los',
       'lucha', 'límites', 'madre', 'mafia', 'maligna', 'malévola',
       'manchega', 'mano', 'marginado', 'marido', 'matrimonio', 'media',
       'mejor', 'mejorar', 'menor', 'mente', 'mercury', 'metódico',
       'mexicano', 'miedos', 'mientras', 'miles', 'mira', 'misión',
       'misma', 'misterio', 'morales', 'mortal', 'muerte', 'muertos',
       'mujer', 'mujeres', 'mundial', 'mundo', 'muy', 'mágico',
       'máquinas', 'más', 'métodos', 'méxico', 'música', 'nadie', 'narra',
       'nazi', 'necesidades', 'niña', 'niño', 'niños', 'novia', 'nueva',
       'nuevo', 'objetivo', 'obligada', 'observa', 'obsesiona',
       'obsesionado', 'ocultos', 'ocupación', 'océano', 'ogro', 'ojos',
       'okja', 'operativo', 'oportunidad', 'organizado', 'orgullo',
       'oscura', 'otro', 'padre', 'padres', 'pantano', 'papel', 'para',
       'paranoia', 'paranormales', 'pareja', 'parisina', 'parlanchín',
       'parque', 'partir', 'pasado', 'paternidad', 'patriarca', 'payaso',
       'pecados', 'pecera', 'peligrosa', 'peligroso', 'pequeño',
       'perfeccionista', 'perfección', 'persiguen', 'perturbadora',
       'pesados', 'pesos', 'pez', 'pianista', 'plantador', 'poco',
       'poder', 'polaco', 'polizón', 'pone', 'por', 'posguerra', 'post',
       'prehistórico', 'prensa', 'prepara', 'presencia', 'princesa',
       'principal', 'procedimiento', 'proceso', 'profesor', 'programador',
       'propia', 'propio', 'propone', 'proponérselo', 'proteger',
       'provoca', 'prueba', 'pruebas', 'psiquiatra', 'pueblo', 'pérdidas',
       'que', 'quedaba', 'queen', 'quien', 'quienes', 'quiere', 'reacio',
       'realidad', 'rebelde', 'recibe', 'recuerdos', 'recuperar',
       'recursos', 'reducido', 'refugio', 'regreso', 'relación', 'repasa',
       'repentina', 'rescatar', 'resistencia', 'resolviendo', 'retirado',
       'robar', 'rodean', 'romance', 'romano', 'san', 'sangrienta',
       'sarcásticas', 'satisfacer', 'se', 'secreto', 'secretos',
       'seguridad', 'sentido', 'sentimental', 'serie', 'setenta',
       'sherlock', 'sicario', 'sicarios', 'siete', 'simulación', 'sin',
       'sindicalista', 'siniestra', 'sistema', 'sistemas',
       'sobreprotector', 'sobrevivir', 'sociedad', 'solitario', 'somete',
       'sospechoso', 'su', 'subconsciente', 'sudamérica', 'sueño',
       'sueños', 'sumerge', 'sumir', 'superhéroes', 'superviviente',
       'surcoreana', 'sus', 'teatro', 'temático', 'termina', 'tierra',
       'tirano', 'titanic', 'todo', 'toma', 'traicionado', 'trampa',
       'transatlántico', 'transforma', 'trapo', 'tras', 'través', 'tres',
       'trágico', 'un', 'una', 'une', 'unidos', 'utiliza', 'valía',
       'vaquero', 'varias', 'varsovia', 've', 'vendados', 'venganza',
       'vengarse', 'verdad', 'veterano', 'viaja', 'viajar', 'viaje',
       'vida', 'vidas', 'violentas', 'visitar', 'viudo', 'viven', 'vivir',
       'volver', 'vuelve', 'ángeles', 'área', 'éticos'], dtype=object)

In [49]:
#Crear matriz de similitud 

matriz_similitud = cosine_similarity(
    matriz_tfid
)
matriz_similitud

array([[1.        , 0.06401851, 0.0905095 , ..., 0.05715021, 0.1284052 ,
        0.17266305],
       [0.06401851, 1.        , 0.06547215, ..., 0.07163359, 0.06436425,
        0.12972311],
       [0.0905095 , 0.06547215, 1.        , ..., 0.04150347, 0.05418986,
        0.04537414],
       ...,
       [0.05715021, 0.07163359, 0.04150347, ..., 1.        , 0.03238018,
        0.08997905],
       [0.1284052 , 0.06436425, 0.05418986, ..., 0.03238018, 1.        ,
        0.0942734 ],
       [0.17266305, 0.12972311, 0.04537414, ..., 0.08997905, 0.0942734 ,
        1.        ]], shape=(50, 50))

In [50]:
#Convertir la matriz a un dataframe

df_similitud = pd.DataFrame(
    matriz_similitud,
    index=df["titulo"],
    columns=df["titulo"]
)

df_similitud.round(2)

titulo                                            El Padrino  ...  Perdida
titulo                                                        ...
El Padrino                                              1.00  ...     0.17
Pulp Fiction                                            0.06  ...     0.13
El Caballero Oscuro                                     0.09  ...     0.05
Origen                                                  0.06  ...     0.12
Matrix                                                  0.03  ...     0.04
Forrest Gump                                            0.06  ...     0.08
Titanic                                                 0.06  ...     0.07
Parásitos                                               0.12  ...     0.09
Interstellar                                            0.08  ...     0.13
Gladiador                                               0.11  ...     0.05
El Señor de los Anillos: La Comunidad del Anillo        0.10  ...     0.10
Jurassic Park                                           0.04  ...     0.12
Toy Story                                               0.05  ...     0.08
Coco                                                    0.11  ...     0.09
Shrek                                                   0.05  ...     0.07
Los Increíbles                                          0.12  ...     0.09
Joker                                                   0.11  ...     0.09
Whiplash                                                0.05  ...     0.07
La La Land                                              0.03  ...     0.06
Get Out                                                 0.08  ...     0.10
Hereditary                                              0.08  ...     0.06
El Conjuro                                              0.10  ...     0.10
It (Eso)                                                0.08  ...     0.11
Bird Box                                                0.08  ...     0.11
Roma                                                    0.14  ...     0.15
El Irlandés                                             0.16  ...     0.19
Historia de un Matrimonio                               0.13  ...     0.10
Okja                                                    0.02  ...     0.03
Enola Holmes                                            0.11  ...     0.06
Bohemian Rhapsody                                       0.12  ...     0.14
Rocky                                                   0.08  ...     0.10
Mad Max: Furia en la Carretera                          0.02  ...     0.07
Kill Bill: Volumen 1                                    0.08  ...     0.09
John Wick                                               0.05  ...     0.06
Django Desencadenado                                    0.06  ...     0.15
La Vida es Bella                                        0.13  ...     0.10
El Pianista                                             0.08  ...     0.09
Amélie                                                  0.07  ...     0.10
Eterno Resplandor de una Mente sin Recuerdos            0.06  ...     0.07
Her                                                     0.01  ...     0.02
Black Swan                                              0.05  ...     0.09
Prisioneros                                             0.15  ...     0.20
Zodiac                                                  0.09  ...     0.13
Seven                                                   0.02  ...     0.06
El Silencio de los Corderos                             0.03  ...     0.07
Buscando a Nemo                                         0.14  ...     0.09
Up                                                      0.10  ...     0.09
El Laberinto del Fauno                                  0.06  ...     0.09
Volver                                                  0.13  ...     0.09
Perdida                                                 0.17  ...     1.00

[50 rows x 50 columns]

In [51]:
#Construir el recomendador

pelicula_seleccionada = "Up"

similitudes = df_similitud[pelicula_seleccionada]

similitudes

titulo
El Padrino                                          0.096482
Pulp Fiction                                        0.048274
El Caballero Oscuro                                 0.028399
Origen                                              0.037736
Matrix                                              0.045955
Forrest Gump                                        0.043754
Titanic                                             0.040497
Parásitos                                           0.019611
Interstellar                                        0.079170
Gladiador                                           0.045190
El Señor de los Anillos: La Comunidad del Anillo    0.092564
Jurassic Park                                       0.027942
Toy Story                                           0.054251
Coco                                                0.070237
Shrek                                               0.122086
Los Increíbles                                      0.046063
Joker                                               0.066746
Whiplash                                            0.044020
La La Land                                          0.031267
Get Out                                             0.107094
Hereditary                                          0.010345
El Conjuro                                          0.064253
It (Eso)                                            0.079900
Bird Box                                            0.025927
Roma                                                0.059530
El Irlandés                                         0.063634
Historia de un Matrimonio                           0.076620
Okja                                                0.057567
Enola Holmes                                        0.046636
Bohemian Rhapsody                                   0.061482
Rocky                                               0.051824
Mad Max: Furia en la Carretera                      0.054107
Kill Bill: Volumen 1                                0.044847
John Wick                                           0.049984
Django Desencadenado                                0.063671
La Vida es Bella                                    0.076633
El Pianista                                         0.069736
Amélie                                              0.022808
Eterno Resplandor de una Mente sin Recuerdos        0.051801
Her                                                 0.034938
Black Swan                                          0.045736
Prisioneros                                         0.115842
Zodiac                                              0.055779
Seven                                               0.045174
El Silencio de los Corderos                         0.035444
Buscando a Nemo                                     0.070147
Up                                                  1.000000
El Laberinto del Fauno                              0.077099
Volver                                              0.059654
Perdida                                             0.091360
Name: Up, dtype: float64

In [52]:
recomendaciones = (
    similitudes.sort_values(ascending=False)
)
recomendaciones

titulo
Up                                                  1.000000
Shrek                                               0.122086
Prisioneros                                         0.115842
Get Out                                             0.107094
El Padrino                                          0.096482
El Señor de los Anillos: La Comunidad del Anillo    0.092564
Perdida                                             0.091360
It (Eso)                                            0.079900
Interstellar                                        0.079170
El Laberinto del Fauno                              0.077099
La Vida es Bella                                    0.076633
Historia de un Matrimonio                           0.076620
Coco                                                0.070237
Buscando a Nemo                                     0.070147
El Pianista                                         0.069736
Joker                                               0.066746
El Conjuro                                          0.064253
Django Desencadenado                                0.063671
El Irlandés                                         0.063634
Bohemian Rhapsody                                   0.061482
Volver                                              0.059654
Roma                                                0.059530
Okja                                                0.057567
Zodiac                                              0.055779
Toy Story                                           0.054251
Mad Max: Furia en la Carretera                      0.054107
Rocky                                               0.051824
Eterno Resplandor de una Mente sin Recuerdos        0.051801
John Wick                                           0.049984
Pulp Fiction                                        0.048274
Enola Holmes                                        0.046636
Los Increíbles                                      0.046063
Matrix                                              0.045955
Black Swan                                          0.045736
Gladiador                                           0.045190
Seven                                               0.045174
Kill Bill: Volumen 1                                0.044847
Whiplash                                            0.044020
Forrest Gump                                        0.043754
Titanic                                             0.040497
Origen                                              0.037736
El Silencio de los Corderos                         0.035444
Her                                                 0.034938
La La Land                                          0.031267
El Caballero Oscuro                                 0.028399
Jurassic Park                                       0.027942
Bird Box                                            0.025927
Amélie                                              0.022808
Parásitos                                           0.019611
Hereditary                                          0.010345
Name: Up, dtype: float64

In [55]:
top_5 = recomendaciones.head(6)
top_5

titulo
Up                                                  1.000000
Shrek                                               0.122086
Prisioneros                                         0.115842
Get Out                                             0.107094
El Padrino                                          0.096482
El Señor de los Anillos: La Comunidad del Anillo    0.092564
Name: Up, dtype: float64